# Generated by Django 3.1.5 on 2021-01-05 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('steam_app_id', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.game')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerSessionLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_session_links', to='api.player')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_player_links', to='api.session')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='sessions',
            field=models.ManyToManyField(through='api.PlayerSessionLink', to='api.Session'),
        ),
    ]
