# Generated by Django 3.1.5 on 2021-01-05 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='sessions',
            field=models.ManyToManyField(related_name='participating_players', through='api.PlayerSessionLink', to='api.Session'),
        ),
        migrations.CreateModel(
            name='GameOwnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_ownership_link', to='api.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_ownership_link', to='api.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='games',
            field=models.ManyToManyField(related_name='players_owning', through='api.GameOwnership', to='api.Game'),
        ),
    ]
