# Generated by Django 3.1.5 on 2021-01-05 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210105_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='games',
            new_name='owned_games',
        ),
    ]
