# Generated by Django 3.1.5 on 2021-01-05 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_auto_20210105_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gameownership',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_ownership_link', to='api.game'),
        ),
        migrations.AlterField(
            model_name='gameownership',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_ownership_link', to='api.player'),
        ),
        migrations.AlterUniqueTogether(
            name='gameownership',
            unique_together={('player', 'game')},
        ),
    ]
