# Generated by Django 3.1.5 on 2021-01-05 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210105_1331'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playersessionlink',
            unique_together={('player', 'session')},
        ),
    ]
